### PR TITLE
Replace `setup.py` with `setup.cfg`

### PR DESCRIPTION
**Pull request by kaxil**
New projects are advised to avoid setup.py configurations (beyond the minimal stub) when custom scripting during the build is not necessary as documented in https://setuptools.pypa.io/en/latest/userguide/quickstart.html

### CODE REVIEW

**Comment by denimalpaca** [comment]
> The tests are failing because the following test expects that dir on PYTHONPATH!
> 
> Can we move it under tests @denimalpaca ?
> 
> https://github.com/astronomer/airflow-provider-great-expectations/blob/main/tests/operators/test_great_expectations.py#L526-L531

Sure, if it'll fix the testing it should be fine. I don't think it'll mess with anything -- @talagluck do you have an opinion here?

**Review by denimalpaca — APPROVED** [review]

**Comment by talagluck** [comment]
I don't have an opinion here - if this is in line with other providers, then it feels reasonable to change.

**Comment by kaxil** [comment]
> I don't have an opinion here - if this is in line with other providers, then it feels reasonable to change.

All those files in the `/include` folder are just for tests, right?

**Comment by denimalpaca** [comment]
they're used for the example DAG, too, so maybe they can be copied over to the `tests/` dir and kept in `include/` as well. Then the example DAG paths don't have to change.

**Pull request merged**
